apiVersion: apps/v1
kind: Deployment
metadata:
  name: novostack-crm-coll-0d0b4412a2be417285ef670f342df0ca-depl
  labels:
    app: novostack-crm-coll-0d0b4412a2be417285ef670f342df0ca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: novostack-crm-coll-0d0b4412a2be417285ef670f342df0ca
  template:
    metadata:
      labels:
        app: novostack-crm-coll-0d0b4412a2be417285ef670f342df0ca
    spec:
      containers:
        - name: novostack-crm-coll-0d0b4412a2be417285ef670f342df0ca
          image: 216084506783.dkr.ecr.ap-south-1.amazonaws.com/backstract_apps:novostack-crm-coll-0d0b4412a2be417285ef670f342df0ca
          imagePullPolicy: Always
          ports:
            - containerPort: 9011